### PR TITLE
-   Fix so UCS nodes do not get "unknown" values for processor-frequency

### PR DESCRIPTION
**Pull request by elgeoman**
or other dmi_config vars.

### CODE REVIEW

**Comment by garlick** [comment]
Thanks!  Looks fine, and I ran 
```
$ cd test
$ make check
```
and everything passed.   It would be good if you could add to this PR  some test output so we are sure not to break this case in the future.  E.g. if platform is UCS,
```
$ sudo lspci -xxx >test/UCS/lspci
$ sudo dmidecode --dump-bin >UCS/dmidecode
$ git add test/UCS/lspci test/UCS/dmidecode
```

**Comment by garlick** [comment]
Thanks @elgeoman - I just tried this and I'm getting a failure on the UCS pci.conf.   The failure goes away if I delete the final blank line from UCS/pci.conf.

Would you mind dropping the blank line and verifying that the test still works on your system?  (Maybe it's something to do with my system)

**Comment by elgeoman** [comment]
@garlick - blank line removed from pci.conf and it works for me still.

**Comment by garlick** [comment]
Excellent thanks!

**Pull request merged**
